### PR TITLE
feat: add new variable stream_ssl_ja3_hash and http_ssl_ja3_hash

### PR DESCRIPTION
**Pull request by oowl**

### CODE REVIEW

**Comment by oowl** [comment]
I suggest using https://github.com/openresty/test-nginx as a test framework for testing purposes, the nginx-ssl-fingerprint module existing testing method is so simple and crude. If you agree, I will continue to help this repo initialization test-nginx workflow.

**Comment by phuslu** [comment]
thanks, let me do a verify.
Considering this issue https://github.com/phuslu/nginx-ssl-fingerprint/issues/44 , I think to the ja3 hash shaould be a lazy and cacheable variable. 
So I'd like to test this PR first.

**Comment by phuslu** [comment]
> I will continue to help this repo initialization test-nginx workflow.

Thanks in advance, feel free to raise it :smile:

**Comment by phuslu** [comment]
I add a debug log like
```patch
diff --git a/src/ngx_http_ssl_fingerprint_module.c b/src/ngx_http_ssl_fingerprint_module.c
index 1b5bb64..1845501 100644
--- a/src/ngx_http_ssl_fingerprint_module.c
+++ b/src/ngx_http_ssl_fingerprint_module.c
@@ -114,6 +114,8 @@ ngx_http_ssl_fingerprint_hash(ngx_http_request_t *r,
         return NGX_ERROR;
     }
 
+    fputs("========================================= clac ja3 hash =================================\n", stderr);
+
     v->data = ngx_pcalloc(r->pool, 32);
 
     ngx_md5_init(&ctx);
```

then test with
```bash
curl -kv https://127.0.0.1:4433/ --next -kv  https://127.0.0.1:4433/
```

found that the $http_ssl_ja3 is not lazy&cacheable.

I think we'd better add new filed (e.g. ngx_str_t  fp_ja3_hash) to nginx.patch https://github.com/phuslu/nginx-ssl-fingerprint/blob/master/patches/nginx-1.25.patch#L54

**Comment by oowl** [comment]
> found that the $http_ssl_ja3 is not lazy&cacheable.
Yeah, it can not be cached when the new ngx_http_request_t is created, I can accept your suggestion, but it can make a break change in our existing version. I am not sure if this performance consideration change is in the current PR or the next PR?

**Comment by phuslu** [comment]
understood, let's merge it first. Then let me try to figure out an improvement withou break change (if exists)

**Comment by phuslu** [comment]
Made it be cacheable in https://github.com/phuslu/nginx-ssl-fingerprint/commit/5e789f14ec588c9298a9f1b763b0be52fdcd5717

But I still have no idea to make it be *lazy*, I doubt it is not doable. 😞

**Pull request merged**
