### PR TITLE
add http2 fingerprint

### PR DESCRIPTION
**Pull request by phuslu**

### CODE REVIEW

**Comment by atyachin** [comment]
Any chance to merge the http2 branch ?
Thanks!

**Comment by phuslu** [comment]
thanks for interests, It need carefully review(internal or public), let me try rebase it to master branch and raise a  request.

**Comment by phuslu** [comment]
@atyachin a inital h2 fp is landed in master branch, still need verification and internal review. But now you could have a try :)

**Comment by atyachin** [comment]
Great, I'll test it.
Thanks much!

**Comment by atyachin** [comment]
@phuslu Thanks again, the h2 fingerprint works!

However, please note that both the h2 fp and the ja3 are slightly different than those reported by this project:
https://github.com/wwhtrbbtt/TrackMe

In the case of ja3, there's a minor difference and in the case of h2 fp, the difference it more visible.
Here's a comparison (curl request under Windows WSL):

nginx-ssl-fingerprint:
`"ja3": "771,4866-4867-4865-49196-49200-159-52393-52392-52394-49195-49199-158-49188-49192-107-49187-49191-103-49162-49172-57-49161-49171-51-157-156-61-60-53-47-255,0-11-10-13172-16-22-23-49-13-43-45-51,29-23-30-25-24-256-257-258-259-260,0-1-2"`
`"http2_fingerprint": "3:100;4:33554432;2:0|33554432|1:0:0:16|m,p,s,a,u,a"`

TrackMe:
`"ja3": "771,4866-4867-4865-49196-49200-159-52393-52392-52394-49195-49199-158-49188-49192-107-49187-49191-103-49162-49172-57-49161-49171-51-157-156-61-60-53-47-255,0-11-10-13172-16-22-23-49-13-43-45-51-21,29-23-30-25-24-256-257-258-259-260,0-1-2"`
`"akamai_fingerprint": "3:100,4:33554432,2:0|33488897|0|m,p,s,a"`

**Comment by phuslu** [comment]
For http2 fingerprint, I believe the tail parts,  `m,p,s,a,u,a` is correct, please see my screenshot of curl

image

For other parts, I'd like wait internal verification results.

**Pull request closed without merging**
